### ISSUE TITLE
Bug: (fill in)installing the sdk fails because of the new svelte5 installation.

### ISSUE THREAD

**Issue by mediocreaverage1** [kinde-oss/kinde-sveltekit-sdk#39]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have checked the latest version of the library to replicate my issue
- [X] I have read the [contributing guidelines](https://github.com/kinde-oss/.github/blob/main/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-oss/.github/blob/main/.github/CODE_OF_CONDUCT.md)

### Describe the issue

created a new sveltekit after they released svelte5. Trying to install your sdk for sveltekit using the command 
npm i @kinde-oss/kinde-auth-sveltekit

I get the following dependency error and unable to install your sdk. You need to update your dependency.

npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: newkit@0.0.1
npm error Found: svelte@5.0.5
npm error node_modules/svelte
npm error   dev svelte@"^5.0.0" from the root project
npm error   peer svelte@"^4.0.0 || ^5.0.0-next.0" from @sveltejs/kit@2.7.2
npm error   node_modules/@sveltejs/kit
npm error     dev @sveltejs/kit@"^2.0.0" from the root project
npm error     peer @sveltejs/kit@"^1.20.4 || ^2.0.0" from @kinde-oss/kinde-auth-sveltekit@1.3.0
npm error     node_modules/@kinde-oss/kinde-auth-sveltekit
npm error       @kinde-oss/kinde-auth-sveltekit@"*" from the root project
npm error   1 more (@sveltejs/vite-plugin-svelte)
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^4.0.0" from @kinde-oss/kinde-auth-sveltekit@1.3.0
npm error node_modules/@kinde-oss/kinde-auth-sveltekit
npm error   @kinde-oss/kinde-auth-sveltekit@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error
npm error For a full report see:
npm error C:\Users\Ad\AppData\Local\npm-cache\_logs\2024-10-23T00_02_30_351Z-eresolve-report.txt
npm error A complete log of this run can be found in: C:\Users\Ad\AppData\Local\npm-cache\_logs\2024-10-23T00_02_30_351Z-debug-0.log
PS D:\mycode\2024\variety\newkit> npm audit fix --force
npm warn using --force Recommended protections disabled.
npm warn audit Updating @sveltejs/kit to 0.0.30, which is a SemVer major change.
npm warn audit Updating @sveltejs/adapter-auto to 0.0.1, which is a SemVer major change.
npm error code EUNSUPPORTEDPROTOCOL
npm error Unsupported URL Type "workspace:": workspace:*
npm error A complete log of this run can be found in: C:\Users\Ad\AppData\Local\npm-cache\_logs\2024-10-23T00_02_51_783Z-debug-0.log
PS D:\mycode\2024\variety\newkit> npm run dev

> newkit@0.0.1 dev
> vite dev

  VITE v5.4.9  ready in 1155 ms

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
8:03:09 PM [vite] Error when evaluating SSR module /src/hooks.server.ts: failed to import "@kinde-oss/kinde-auth-sveltekit"
|- Error: Cannot find module '@kinde-oss/kinde-auth-sveltekit' imported from 'D:/mycode/2024/variety/newkit/src/hooks.server.ts'
    at nodeImport (file:///D:/mycode/2024/variety/newkit/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:53036:19)
    at ssrImport (file:///D:/mycode/2024/variety/newkit/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52903:22)
    at eval (D:/mycode/2024/variety/newkit/src/hooks.server.ts:3:50)
    at instantiateModule (file:///D:/mycode/2024/variety/newkit/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52961:11)

8:03:09 PM [vite] Pre-transform error: Failed to load url @kinde-oss/kinde-auth-sveltekit (resolved id: @kinde-oss/kinde-auth-sveltekit) in D:/mycode/2024/variety/newkit/src/hooks.server.ts. Does the file exist?
Error: Cannot find module '@kinde-oss/kinde-auth-sveltekit' imported from 'D:/mycode/2024/variety/newkit/src/hooks.server.ts'
    at nodeImport (file:///D:/mycode/2024/variety/newkit/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:53036:19) 
    at ssrImport (file:///D:/mycode/2024/variety/newkit/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52903:22)  
    at eval (D:/mycode/2024/variety/newkit/src/hooks.server.ts:3:50)
    at instantiateModule (file:///D:/mycode/2024/variety/newkit/node_modules/vite/dist/node/chunks/dep-Cyk9bIUq.js:52961:11) {
  code: 'ERR_MODULE_NOT_FOUND'
}
8:03:21 PM [vite] page reload src/hooks.server.ts
8:03:24 PM [vite] page reload src/hooks.server.ts (x2)

 *  History restored 

PS D:\mycode\2024\variety\newkit> npm i @kinde-oss/kinde-auth-sveltekit
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: newkit@0.0.1
npm error Found: svelte@5.0.5
npm error node_modules/svelte
npm error   dev svelte@"^5.0.0" from the root project
npm error   peer svelte@"^4.0.0 || ^5.0.0-next.0" from @sveltejs/kit@2.7.2
npm error   node_modules/@sveltejs/kit
npm error     dev @sveltejs/kit@"^2.0.0" from the root project
npm error     peer @sveltejs/kit@"^1.20.4 || ^2.0.0" from @kinde-oss/kinde-auth-sveltekit@1.3.0
npm error     node_modules/@kinde-oss/kinde-auth-sveltekit
npm error       @kinde-oss/kinde-auth-sveltekit@"*" from the root project
npm error   1 more (@sveltejs/vite-plugin-svelte)
npm error
npm error Could not resolve dependency:
npm error peer svelte@"^4.0.0" from @kinde-oss/kinde-auth-sveltekit@1.3.0
npm error node_modules/@kinde-oss/kinde-auth-sveltekit
npm error   @kinde-oss/kinde-auth-sveltekit@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error

### Library URL

https://github.com/kinde-oss/kinde.sveltekit

### Library version

1.30

### Operating system(s)

Windows

### Operating system version(s)

win11 h21

### Additional information

You need to update the sdk with the new dependency.

**Comment by DanielRivers** [comment]
We are working to resolve this. Will update soon

**Comment by mediocreaverage** [comment]
> We are working to resolve this. Will update soon

I need to start a new project with requirement for sevlte5. Any update regarding this issue?

**Comment by DaniilKubarenko** [comment]
Also interested in this. I want to give Kinde a go.

**Comment by DanielRivers** [comment]
Svelte 5 support is in review will be out soon

**Comment by mattjsingleton** [comment]
Also looking forward to this fix!

**Comment by DanielRivers** [comment]
PR is open, I will look to get this released by the weekend UTC

**Comment by mediocreaverage1** [comment]
> PR is open, I will look to get this released by the weekend UTC

 Daniel. We're rooting for you. You can do this and make us all happy.

Let's go.

**Comment by DanielRivers** [comment]
This has been released v2+ of the SDK support for Svelte5
